//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESDBHandler.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptTemplate
    {
        public int Id { get; set; }
        public string sd_st_attr_general_method_name { get; set; }
        public string sd_snippet_group_name { get; set; }
        public string sosv_setup_name { get; set; }
    }
}
