/*
 * Script Generator
 *
 * To get the template, product, and raw data from the database
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ScriptGenerator.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse2002 : IEquatable<InlineResponse2002>
    { 
        /// <summary>
        /// Gets or Sets RawDataId
        /// </summary>

        [DataMember(Name="rawDataId")]
        public string RawDataId { get; set; }

        /// <summary>
        /// Gets or Sets RawDataContent
        /// </summary>

        [DataMember(Name="rawDataContent")]
        public string RawDataContent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2002 {\n");
            sb.Append("  RawDataId: ").Append(RawDataId).Append("\n");
            sb.Append("  RawDataContent: ").Append(RawDataContent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse2002)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse2002 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse2002 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2002 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    RawDataId == other.RawDataId ||
                    RawDataId != null &&
                    RawDataId.Equals(other.RawDataId)
                ) && 
                (
                    RawDataContent == other.RawDataContent ||
                    RawDataContent != null &&
                    RawDataContent.Equals(other.RawDataContent)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (RawDataId != null)
                    hashCode = hashCode * 59 + RawDataId.GetHashCode();
                    if (RawDataContent != null)
                    hashCode = hashCode * 59 + RawDataContent.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse2002 left, InlineResponse2002 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse2002 left, InlineResponse2002 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
